### ISSUE TITLE
glib related bug?

### ISSUE THREAD

**Issue by zengyang2003** [Douane/Douane#36] opened 2014-11-08 06:37 UTC
Various occasions find this on mint:

(douane-dialog:23554): glibmm-WARNING **: Glib::Error::throw_exception():
  unknown error domain 'rsvg-error-quark': throwing generic Glib::Error exception

terminate called after throwing an instance of 'Glib::Error'

**Comment by unidesign** [comment] 2015-05-13 14:01
I want to say that I get the same error, too. Douane doesn't work on Linux Mint.
After compilation which runs completely successfull (unless twitter window due to bad key, but that's totally okay imho) I dont get any icon or similar. When I start `sudo service douane start` and than `douane-configurator` the configurator starts and directly two windows for active apps like `firefox` ask me to allow or deny. When I press something (doesnt matter if allow or deny) the program is blocked. After that I always get the `glibmm-WARNING`.

I can only give you the log of my active terminal, hopefully you can read something out of it.

```
tim@pc ~/Douane/douane-configurator $ douane-configurator
 * Starting the douaned daemon                                           [ OK ] 
 * Stopping douaned daemon                                               [ OK ] 
 * Starting the douaned daemon                                           [ OK ] 
 * Stopping douaned daemon                                               [ OK ] 
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/douane/dbus.py", line 33, in call
    return self.__service_douane.get_dbus_method(method, self.__dbus_serive_name)(argument)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.84 was not provided by any .service files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/douane/gui/mainwindow.py", line 110, in on_submenuDelete_clicked
    if(self.__dbus_client.call("DeleteRule", model.get_value(tree_iter, 1))):
  File "/usr/local/lib/python3.4/dist-packages/douane/dbus.py", line 35, in call
    raise DBusServiceNotFoundError(error)
douane.dbus.DBusServiceNotFoundError: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.84 was not provided by any .service files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/douane/gui/mainwindow.py", line 117, in on_submenuDelete_clicked
    except douane.dbus.DBusServiceNotFoundError as error:
NameError: name 'douane' is not defined
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/douane/dbus.py", line 33, in call
    return self.__service_douane.get_dbus_method(method, self.__dbus_serive_name)(argument)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.84 was not provided by any .service files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/douane/gui/mainwindow.py", line 110, in on_submenuDelete_clicked
    if(self.__dbus_client.call("DeleteRule", model.get_value(tree_iter, 1))):
  File "/usr/local/lib/python3.4/dist-packages/douane/dbus.py", line 35, in call
    raise DBusServiceNotFoundError(error)
douane.dbus.DBusServiceNotFoundError: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.84 was not provided by any .service files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/douane/gui/mainwindow.py", line 117, in on_submenuDelete_clicked
    except douane.dbus.DBusServiceNotFoundError as error:
NameError: name 'douane' is not defined
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/douane/dbus.py", line 33, in call
    return self.__service_douane.get_dbus_method(method, self.__dbus_serive_name)(argument)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.84 was not provided by any .service files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/douane/gui/mainwindow.py", line 110, in on_submenuDelete_clicked
    if(self.__dbus_client.call("DeleteRule", model.get_value(tree_iter, 1))):
  File "/usr/local/lib/python3.4/dist-packages/douane/dbus.py", line 35, in call
    raise DBusServiceNotFoundError(error)
douane.dbus.DBusServiceNotFoundError: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.84 was not provided by any .service files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/douane/gui/mainwindow.py", line 117, in on_submenuDelete_clicked
    except douane.dbus.DBusServiceNotFoundError as error:
NameError: name 'douane' is not defined
 * Starting the douaned daemon                                           [ OK ] 
 * Stopping douaned daemon                                               [ OK ] 
```

And

```
tim@pc ~ $ /opt/douane/bin/douane-dialog

(douane-dialog:18789): glibmm-WARNING **: Glib::Error::throw_exception():
  unknown error domain 'rsvg-error-quark': throwing generic Glib::Error exception

terminate called after throwing an instance of 'Glib::Error'
```

Btw. if your software would work on Linux Mint aswell it would be very nice because it fits my needs very well, thank you.

**Comment by zedtux** [comment] 2015-05-13 17:17
Alright so this seems to be a confirmed bug at least on Mint.

Recently I've switched from Ubuntu to Debian so I will check if I have the error like you.

**Comment by zedtux** [comment] 2015-05-14 08:02
@TheCherry you can enable debug using the `--debug` flag when starting the `douane-dialog` process

**Comment by zedtux** [comment] 2015-05-14 08:07
I'm downloading a VirtualBox image named "LinuxMint 14 x86 Cinnamon". Hopefully this will cover your case.

**Comment by zedtux** [comment] 2015-05-14 08:14
As I have re-opened the issue in the right project I'm closing this one.

**Closed by zedtux** 2015-05-14 08:14 UTC
Labels: bug

**Comment by zedtux** [comment] 2015-05-14 08:22
I've finally found a 17 version image
