### ISSUE TITLE
douane-dialog build issue on Fedora 22/23

### ISSUE THREAD

**Issue by shpedoikal** [Douane/Douane#51] opened 2015-11-04 18:22 UTC
Build log:

http://pastebin.com/crKBzB3E

**Comment by zedtux** [comment] 2015-11-04 18:31
It looks like a dependency conflict to me but not sure.

**Comment by shpedoikal** [comment] 2015-12-04 14:55
Forgot to mention that I had a huge number of errors until I manually added -std=c++11 to the build. After that I got this smaller number of errors.

Can you post your compiler version?  Thanks

**Comment by shpedoikal** [comment] 2015-12-04 15:04
I also see these errors on Fedora 23, so I've updated the title to reflect that.

**Comment by czapa-ols** [comment] 2016-02-28 13:49
The problem is within dbus-c++: the collision is between the macro bind_property in dbus-c++/interface.h and the method bind_property in glibmm/binding.h

`#include <gtkmm.h>` before `#include<dbus-c++/dbus.h>` in dbus/douane.h and dbus/dbus_client.h seams to fix issue (at least dialog builds)

**Comment by zedtux** [comment] 2017-07-20 09:47
@shpedoikal do you have any news since @czapa-ols did a PR which has been merged in master?

**Comment by intika** [comment] 2018-04-12 07:42
had the same issue on a fedora like system... and fixed it @zedtux merged the fix can you git clone and try again

**Comment by intika** [comment] 2018-04-13 17:08
should be closed (also its a duplicate of some start daemon issues)

**Comment by zedtux** [comment] 2018-04-13 18:12
@intika please link issues together if there are duplicates.

@shpedoikal and @czapa-ols can you please update this issue?

**Comment by zedtux** [comment] 2018-06-13 10:53
This repo has moved to GitLab and this issue has been imported. You can access it [here](https://gitlab.com/douaneapp/Douane/issues/51).

**Closed** 2019-02-14 14:51 UTC
Labels: Compilation issue
