### ISSUE TITLE
Dialog Window don't appear, but connections are blocked

### ISSUE THREAD

**Issue by saitam1** [Douane/Douane#80] opened 2018-02-15 16:06 UTC
When I turn on `Douane` with the configurator or start it via terminal the dialog window doesnt' appear on every app. It won't recognize `Geary Mail` and a few other apps, so the connection on them is blocked and the apps aren't usable. There is also no possibilty to add a rule for an app manually. 
![error mail](https://user-images.githubusercontent.com/23245678/36266637-3c3e2f42-1272-11e8-8964-2a8ee58afd78.png)

**UPDATE:**
Just in case you are interested in the apps, on which no dialog window appears. So far:
`FileZilla`
`DBeaver`

After several restarts the following apps were recognized:
`Geary`, `Rambox`, `Wunderlistux` 

If certain apps are not recognized, then it is really hard to rely on this software, because it may just not show up the malicious app.

I guess there is no solution right now for this problem?

**Comment by zedtux** [comment] 2018-02-17 11:34
Thank you @saitam1 for this issue.

The described scenario looks like the dialog process has crashed.

 - Have you checked that all the Douane processes are running when this happen?
 - Have you checked the log files?

**Comment by danarmstrong** [comment] 2018-03-03 08:50
I am experiencing this as well. The dialog segfaults when a new alert is triggered. Usually if I restart douane-dialog a few times the problem is corrected and the dialog appears allowing me to allow/deny the applications. Then it happens again the next time a new app triggers it. In every instance this has occurred it is when multiple processes trigger the dialog at the same time. For example, Tor contains an entry for Tor and Firefox and causes the dialog to segfault. When I first installed douane, there were about 9 entries and I had to restart douane-dialog 9 times before the crashes stopped.

**Comment by danarmstrong** [comment] 2018-03-03 08:51
Out of curiosity I just started an application that I knew would only have a single process trigger the dialog (hexchat) and the dialog did not crash on that one. This issue appears to be related to multiple entries on the dialog.

**Comment by zedtux** [comment] 2018-03-05 06:26
Hey nice catch @danarmstrong ! 👍 
So the dialog process is suffering a concurrence issue. @danarmstrong could you please open an issue on [the right project](https://github.com/Douane/douane-dialog) summarising what you discovered?

**Comment by zedtux** [comment] 2018-03-06 06:19
Thank you @danarmstrong for having created the issue https://github.com/Douane/douane-dialog/issues/13, I'm now closing this one.

**Closed by zedtux** 2018-03-06 06:19 UTC
Labels: Information needed
